#!/bin/bash

set -eu -o pipefail

readonly ssh_keys="${HOME}/.ssh/id_rsa_yellowtent"

if [[ "$#" != "1" ]]; then
    echo "Missing cloudron IP argument";
    exit 1;
fi

if [[ ! -f "${ssh_keys}" ]]; then
    echo "yellowtent ssh key is missing"
    exit 1
fi

ssh root@$1 -p 919 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ConnectTimeout=10 -i "${ssh_keys}"
