#!/bin/bash

set -eu

readonly SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# reset sudo timestamp to avoid wrong success
sudo -k || sudo --reset-timestamp

# checks if all scripts are sudo access
scripts=("${SOURCE_DIR}/src/scripts/rmappdir.sh" \
         "${SOURCE_DIR}/src/scripts/createappdir.sh" \
         "${SOURCE_DIR}/src/scripts/reloadnginx.sh" \
         "${SOURCE_DIR}/src/scripts/backupbox.sh" \
         "${SOURCE_DIR}/src/scripts/backupapp.sh" \
         "${SOURCE_DIR}/src/scripts/restoreapp.sh" \
         "${SOURCE_DIR}/src/scripts/reboot.sh" \
         "${SOURCE_DIR}/src/scripts/reloadcollectd.sh")

for script in "${scripts[@]}"; do
    if [[ $(sudo -n "${script}" --check 2>/dev/null) != "OK" ]]; then
        echo ""
        echo "${script} does not have sudo access."
        echo "You have to add the lines below to /etc/sudoers.d/yellowtent."
        echo ""
        echo 'Defaults!${script} env_keep="HOME NODE_ENV"'
        echo "${USER} ALL=(ALL) NOPASSWD: ${script}"
        echo ""
        exit 1
    fi
done

if ! docker inspect girish/test:0.1.0 >/dev/null 2>/dev/null; then
    echo "docker pull girish/test:0.1.0 for tests to run"
    exit 1
fi

if ! docker inspect girish/redis:0.4 >/dev/null 2>/dev/null; then
    echo "docker pull girish/redis:0.4 for tests to run"
    exit 1
fi

if ! docker inspect girish/mysql:0.4 >/dev/null 2>/dev/null; then
    echo "docker pull girish/mysql:0.4 for tests to run"
    exit 1
fi

if ! docker inspect girish/postgresql:0.4 >/dev/null 2>/dev/null; then
    echo "docker pull girish/postgresql:0.4 for tests to run"
    exit 1
fi

exit 0
