#!/bin/bash

# If you change the infra version, be sure to put a warning
# in the change log

INFRA_VERSION=16

# WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
# These constants are used in the installer script as well
BASE_IMAGE=cloudron/base:0.6.0
MYSQL_IMAGE=cloudron/mysql:0.6.0
POSTGRESQL_IMAGE=cloudron/postgresql:0.6.0
MONGODB_IMAGE=cloudron/mongodb:0.6.0
REDIS_IMAGE=cloudron/redis:0.6.1 # if you change this, fix src/addons.js as well
MAIL_IMAGE=cloudron/mail:0.6.0
GRAPHITE_IMAGE=cloudron/graphite:0.6.0

